package com.kapok.apps.maple.xdt.classlist.bean

data class TeacherHomeWorkNoticeBean(
    val classId: Int,
    val className: String,
    val content: String,
    val deadline: String,
    val gmtCreate: String,
    val grade: String,
    val gradeId: Int,
    val images: String,
    val isTeacherLeader: Boolean,
    val readStatus: Int,
    val receiptStatus: Int,
    val remainTime: String,
    val replyStatus: Int,
    val schoolId: Int,
    val schoolName: String,
    val startYear: Int,
    val state: Int,
    val studentCount: Int,
    val studentId: Int,
    val subStudentCount: Int,
    val subjectId: Int,
    val subjectName: String,
    val submitStatus: Int,
    val teacherAvatar: String?,
    val teacherId: Int,
    val teacherName: String,
    val title: String,
    val type: Int,
    val unSubStudentCount: Int,
    val workId: Int,
    val workType: Int,
    val workTypeDesc: String
)